# Jekyll Defaults
title: jihyoyo blog
description: Jr. Machine Learning Engineer
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://jihyo-jeon.github.io/"
github: https://github.com/JIHYO-JEON/JIHYO-JEON.github.io
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
